// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-salons.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.1.11";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.50.0";
function getSupabase() {
  const url = process.env.SUPABASE_URL;
  const key = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
  if (!url || !key) {
    throw new Error("Supabase environment is not configured");
  }
  return createClient(url, key, {
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/search-salons.ts
var search_salons_default = defineTool({
  name: "search_salons",
  title: "Search trade shows",
  description: "Search French professional trade shows (salons) listed on Lotexpo. Filter by keyword, sector label, or city. Returns upcoming and ongoing salons by default.",
  inputSchema: {
    query: z.string().optional().describe("Free-text keyword matched against the salon name."),
    sector: z.string().optional().describe("Sector label, e.g. 'Industrie & Production' or 'Sant\xE9 & M\xE9dical'."),
    city: z.string().optional().describe("City name, e.g. 'Paris' or 'Lyon'."),
    includePast: z.boolean().optional().describe("Set true to include salons that have already ended. Default false."),
    limit: z.number().int().optional().describe("Maximum number of results to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, sector, city, includePast, limit }) => {
    const supabase = getSupabase();
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    let q = supabase.from("events").select(
      "nom_event, slug, date_debut, date_fin, ville, nom_lieu, type_event, secteur, affluence, url_site_officiel"
    ).eq("visible", true).not("is_test", "is", true).order("date_debut", { ascending: true }).limit(max);
    if (query) q = q.ilike("nom_event", `%${query}%`);
    if (city) q = q.ilike("ville", `%${city}%`);
    if (sector) q = q.contains("secteur", [sector]);
    if (!includePast) q = q.or(`date_fin.gte.${today},date_debut.gte.${today}`);
    const { data, error } = await q;
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({
      name: r.nom_event,
      slug: r.slug,
      url: r.slug ? `https://lotexpo.com/events/${r.slug}` : null,
      start_date: r.date_debut,
      end_date: r.date_fin,
      city: r.ville,
      venue: r.nom_lieu,
      type: r.type_event,
      sectors: Array.isArray(r.secteur) ? r.secteur : [],
      attendance: r.affluence,
      official_site: r.url_site_officiel
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, salons: rows }
    };
  }
});

// src/lib/mcp/tools/get-salon.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.1.11";
var get_salon_default = defineTool2({
  name: "get_salon",
  title: "Get trade show details",
  description: "Get the full public details of a single Lotexpo trade show (salon) by its slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("The salon slug, e.g. 'sido-2026'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = getSupabase();
    const { data, error } = await supabase.from("events").select(
      "nom_event, slug, date_debut, date_fin, ville, nom_lieu, rue, code_postal, pays, type_event, secteur, affluence, tarif, description_event, description_enrichie, url_site_officiel, url_image, is_b2b"
    ).eq("slug", slug).eq("visible", true).not("is_test", "is", true).maybeSingle();
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    if (!data) {
      return {
        content: [{ type: "text", text: `No salon found for slug "${slug}".` }],
        isError: true
      };
    }
    const salon = {
      name: data.nom_event,
      slug: data.slug,
      url: data.slug ? `https://lotexpo.com/events/${data.slug}` : null,
      start_date: data.date_debut,
      end_date: data.date_fin,
      city: data.ville,
      venue: data.nom_lieu,
      street: data.rue,
      postal_code: data.code_postal,
      country: data.pays,
      type: data.type_event,
      sectors: Array.isArray(data.secteur) ? data.secteur : [],
      attendance: data.affluence,
      pricing: data.tarif,
      description: data.description_enrichie ?? data.description_event,
      official_site: data.url_site_officiel,
      image: data.url_image,
      b2b: data.is_b2b
    };
    return {
      content: [{ type: "text", text: JSON.stringify(salon, null, 2) }],
      structuredContent: { salon }
    };
  }
});

// src/lib/mcp/tools/list-sectors.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_sectors_default = defineTool3({
  name: "list_sectors",
  title: "List trade show sectors",
  description: "List the business sectors that Lotexpo trade shows are classified under, with the number of upcoming salons per sector. Use the returned labels with search_salons.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async () => {
    const supabase = getSupabase();
    const today = (/* @__PURE__ */ new Date()).toISOString().slice(0, 10);
    const { data, error } = await supabase.from("events").select("secteur").eq("visible", true).not("is_test", "is", true).or(`date_fin.gte.${today},date_debut.gte.${today}`);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const counts = /* @__PURE__ */ new Map();
    for (const row of data ?? []) {
      const labels = Array.isArray(row.secteur) ? row.secteur : [];
      for (const label of labels) {
        if (typeof label === "string" && label.trim()) {
          counts.set(label, (counts.get(label) ?? 0) + 1);
        }
      }
    }
    const sectors = [...counts.entries()].map(([label, upcomingSalons]) => ({ label, upcomingSalons })).sort((a, b) => b.upcomingSalons - a.upcomingSalons);
    return {
      content: [{ type: "text", text: JSON.stringify(sectors, null, 2) }],
      structuredContent: { count: sectors.length, sectors }
    };
  }
});

// src/lib/mcp/tools/search-exhibitors.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^4.1.11";
var search_exhibitors_default = defineTool4({
  name: "search_exhibitors",
  title: "Search exhibitors",
  description: "Search companies (exhibitors) referenced on Lotexpo by name. Returns approved, public exhibitor profiles.",
  inputSchema: {
    query: z3.string().min(1).describe("Company name or partial name to search for."),
    limit: z3.number().int().optional().describe("Maximum number of results to return (default 20, max 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const supabase = getSupabase();
    const max = Math.min(Math.max(limit ?? 20, 1), 50);
    const { data, error } = await supabase.from("exhibitors").select("name, slug, website, description, logo_url").eq("approved", true).not("is_test", "is", true).ilike("name", `%${query}%`).order("name", { ascending: true }).limit(max);
    if (error) {
      return { content: [{ type: "text", text: `Error: ${error.message}` }], isError: true };
    }
    const rows = (data ?? []).map((r) => ({
      name: r.name,
      slug: r.slug,
      url: r.slug ? `https://lotexpo.com/exposants/${r.slug}` : null,
      website: r.website,
      description: r.description,
      logo: r.logo_url
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { count: rows.length, exhibitors: rows }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "lotexpo-mcp",
  title: "Lotexpo MCP",
  version: "0.1.0",
  instructions: "Tools for Lotexpo, the reference directory of French professional trade shows (salons) and their exhibitors. Use `list_sectors` to discover sector labels, `search_salons` to find upcoming trade shows by keyword/sector/city, `get_salon` to fetch full details of one salon, and `search_exhibitors` to look up exhibiting companies.",
  tools: [search_salons_default, get_salon_default, list_sectors_default, search_exhibitors_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
