
name: Import Communes
on:
  workflow_dispatch:
jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer uniquement dans un dossier isolé
      - run: |
          mkdir temp-import
          cd temp-import
          npm init -y
          # Forcer le mode ESM
          echo '{ "type": "module" }' > package.json
          npm install node-fetch@3 @supabase/supabase-js

      # Exécuter le script ESM renommé
      - run: |
          node \
            --experimental-specifier-resolution=node \
            scripts/importCommunesFromAPI.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
