
name: Import Communes
on:
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Installer uniquement les dépendances requises, sans les enregistrer,
      # et en ignorant les peer-deps (évite tout conflit React)
      - run: npm install node-fetch@3 @supabase/supabase-js --no-save --legacy-peer-deps

      # Exécuter le script .mjs (ESM)
      - run: node --experimental-specifier-resolution=node scripts/importCommunesFromAPI.mjs
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_KEY: ${{ secrets.SUPABASE_SERVICE_KEY }}
